name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - env:
          DOCKER_BUILDKIT: 1
          DOCKER_HUB_REGISTRY_USERNAME:
            ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
          DOCKER_HUB_REGISTRY_PASSWORD:
            ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
          GITHUB_REGISTRY_USERNAME: ${{ github.actor }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        name: Build and release
        run: |
          # GitHub Packages Registry
          echo $GITHUB_REGISTRY_PASSWORD | docker login ghcr.io --username $GITHUB_REGISTRY_USERNAME --password-stdin

          # Docker Hub
          echo $DOCKER_HUB_REGISTRY_PASSWORD | docker login registry.hub.docker.com --username $DOCKER_HUB_REGISTRY_USERNAME --password-stdin

          VERSION=`cat ./VERSION`
          docker buildx build \
            --build-arg VERSION=$VERSION \
            --output=type=registry \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/ridedott/pubsub-emulator:latest \
            --tag ghcr.io/ridedott/pubsub-emulator:$VERSION \
            --tag registry.hub.docker.com/ridedott/pubsub-emulator:latest \
            --tag registry.hub.docker.com/ridedott/pubsub-emulator:$VERSION \
            .
