name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: |
          docker build --tag pubsub-emulator .
      - name: Release
        env:
          GITHUB_REGISTRY_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_REGISTRY_PASSWORD }}
          DOCKER_HUB_REGISTRY_USERNAME:
            ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
          DOCKER_HUB_REGISTRY_PASSWORD:
            ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
        run: |
          VERSION=`docker run pubsub-emulator gcloud components list --filter pubsub-emulator --format="value(latest_version_string)" |& tail -n 1`
          # GitHub Package Registry
          echo $GITHUB_REGISTRY_PASSWORD | docker login docker.pkg.github.com --username $GITHUB_REGISTRY_USERNAME --password-stdin
          docker tag pubsub-emulator docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:latest
          docker tag pubsub-emulator docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:$VERSION
          docker push docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:latest
          docker push docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:$VERSION
          # Docker Hub
          echo $DOCKER_HUB_REGISTRY_PASSWORD | docker login registry.hub.docker.com --username $DOCKER_HUB_REGISTRY_USERNAME --password-stdin
          docker tag pubsub-emulator registry.hub.docker.com/ridedott/pubsub-emulator:latest
          docker tag pubsub-emulator registry.hub.docker.com/ridedott/pubsub-emulator:$VERSION
          docker push registry.hub.docker.com/ridedott/pubsub-emulator:latest
          docker push registry.hub.docker.com/ridedott/pubsub-emulator:$VERSION
