name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build
        run: |
          docker build --tag image .
          VERSION=`docker run image gcloud components list --filter pubsub-emulator --format="value(latest_version_string)" |& tail -n 1`
          docker tag image docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:latest
          docker tag image docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:$VERSION
      - name: Release
        env:
          GITHUB_REGISTRY_USERNAME: ${{ secrets.GITHUB_REGISTRY_USERNAME }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_REGISTRY_PASSWORD }}
        run: |
          echo $GITHUB_REGISTRY_PASSWORD | docker login docker.pkg.github.com --username $GITHUB_REGISTRY_USERNAME --password-stdin
          docker push \
            docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:latest
          docker push \
            docker.pkg.github.com/ridedott/pubsub-emulator-docker/pubsub-emulator:$VERSION
